spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxidb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    job:
      enabled: false
      names: ${batch.job.name:taxiDataImportJob}  # Default if not specified
    jdbc:
      initialize-schema: embedded
      platform: postgresql
  sql:
    init:
      mode: always
      platform: postgresql
  flyway:
    enabled: false

batch:
  job:
    name: taxiDataImportJob
    step:
      name: importTaxiDataStep
    chunk-size: 1000
    retry:
      limit: 3
    skip:
      limit: 10

input:
  file:
    path: ./data/yellow_tripdata_2024-01.parquet

logging:
  level:
    com.taxidata: DEBUG
    org.springframework.batch: INFO 