spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxidb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  batch:
    job:
      enabled: false
      names: ${batch.job.name:taxiDataImportJob}  # Default if not specified
    jdbc:
      initialize-schema: always
    sql:
      init:
        mode: always
        platform: postgresql
  flyway:
    enabled: true
    clean:
      disabled: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    clean-on-validation-error: true

batch:
  job:
    name: taxiDataImportJob
    step:
      name: importTaxiDataStep
    chunk-size: 1000
    retry:
      limit: 3
    skip:
      limit: 10

input:
  file:
    path: ./data/yellow_tripdata_2024-01.parquet

logging:
  level:
    com.taxidata: DEBUG
    org.springframework.batch: INFO 