spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxidb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # CAUTION: Use only in development mode. When dev profile enabled, cleans up the database on startup
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
  batch:
    job:
      enabled: false
      names: ${batch.job.name:taxiDataImportJob}  # Default if not specified
    jdbc:
      initialize-schema: always
    sql:
      init:
        mode: always
        platform: postgresql
  flyway:
    enabled: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/**/
    graphiql:
      enabled: true  # Enable GraphiQL UI for testing

batch:
  job:
    name: taxiDataImportJob
    step:
      name: importTaxiDataStep
    chunk-size: 1000
    retry:
      limit: 3
    skip:
      limit: 10

input:
  file:
    path: ./data/yellow_tripdata_2024-01.parquet

logging:
  level:
    com.taxidata: DEBUG
    org.springframework.batch: INFO