spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxidb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
      platform: postgresql
  sql:
    init:
      mode: always
      platform: postgresql
  flyway:
    enabled: false

input:
  file:
    path: ./data/yellow_tripdata_2024-01.parquet
    batch-size: 1000

logging:
  level:
    com.taxidata: DEBUG
    org.springframework.batch: INFO 